name: Build
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0

      - uses: gradle/wrapper-validation-action@v1.0.6

      - name: Set up JDK 17
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.2
        with:
          arguments: build
